### ISSUE TITLE
Question: Can a plain text password be recovered from a hash?

### ISSUE THREAD

**Issue by clockwork189** [barrysteyn/node-scrypt#126]
Hi there,

Thanks for creating this library and have been using it since version 4, currently on 5.4.1 and upgrading to 6 soon. I am doing a quick backend security audit of my system and I was wondering, if it is possible to get the plain text password from the hash(that would be stored in the database in the place of a plain text password).The following is how I would encrypt and store the password in the db:

`var scryptParameters = scrypt.paramsSync(0.5);`
`var kdfResult = scrypt.kdfSync("password", scryptParameters);`
` user.password = kdfResult.toString('base64');`

So, if I were to somehow get the user.password value, which would be the KDF stored. If a malicious attacker were to gain access to our codebase and figure out our hashing parameters and know that we are using scrypt, could they use scrypt to decrypt that key?

Thanks

**Comment by Demurgos** [comment]
Hi,
`scrypt` - as any hash function - is not symmetric. It means that **there is no known method to retrieve the input (password)** that produced the output unless you try every possible input (brute-force attack).
For some weaker hashes (such as `MD5`), the cost of hash is low enough and the result space is small enough that a brute-force or rainbow-table attack might be succesful.

In this regard, `scrypt` is superior to other hashes because you can parameter it to be as slow as you want. You want it to be fast enough so a legit authentication is quick enough but slow enough so a brute-force attack would be impossible. (It also uses a lot of memory to limit parallelization)

I am not an expert, so it would be nice if @barrysteyn or a more knowledgeable person could complete this answer.

**Comment by barrysteyn** [comment]
@Demurgos Your answer is good. I would just add that unfortunately, choosing scrypt params is still a bit of an art. However, as of now, it is the still the best cryptographic hash algorithm that I know of.

**Comment by clockwork189** [comment]
Awesome, thank you both of you.
