### ISSUE TITLE
The HMAC_SHA256(scrypt, "SHA-128/256"(params)) comparison at the end of the scrypt call does not add security

### ISSUE THREAD

**Issue by oconnore** [barrysteyn/node-scrypt#46]
The documentation claims, 

> What is essential in terms of security is hash integrity (meaning that no part of the hashed output can be changed) and that the original password cannot be determined from the hashed output (this is why you are using scrypt - because it does this in a good way). Bytes 64 to 95 is where all this happens.

If an attacker controls the scrypt output referenced by the verifier (i.e. integrity checks would be necessary), they can modify the resulting blob to be any password they like, and you are hosed with or without this construct. 

This approach just adds complexity and runtime to the otherwise simple operation of checking that `scrypt(password, salt, params) === stored_verifier_blob`, and adds an unneeded 16 byte checksum to the output.

**Comment by dodtsair** [comment]
I would tend to agree.  Coming from a java background using https://github.com/wg/scrypt the derived key is included in the payload and there is no HMAC on the scrypt parameters.  I do not see how the HMAC gives more security.

**Comment by barrysteyn** [comment]
There are a few reasons why I am doing this:

 1. Probably the most important reason: Colin Percival (the creator of Scrypt) is doing this. In fact, this is his code, I am not touching it (I am merely writing the Node interface to his C++ code).
 2. Integrity is not only the case when someone controls the verifier. It essentially thwarts any type of active attack (or at least, that is what it's purpose is). If you look at the verification code, there are many "layers" before the actual scrypt kdf is checked. If any of those "layers" fails, a false result is returned. One of the "layers" is to immediately check message integrity, and if it does not work out, then return false ASAP. You may be thinking this is an overkill (you stated so in the issue description). I can assure you that it is not since an active attacker may have the ability to do damage but just not in the way you are thinking.
 3. If you just want to check the kdf, then do not use the hash. You can use the kdf and make your own scheme.

To conclude: We can debate this for ages, and yes, I concede that you may have some points. But for the reasons outlined above, I am going to leave the code be.

**Comment by jeremejevs** [comment]
> Colin Percival (the creator of Scrypt) is doing this

What's his rationale? Is it published anywhere?

> an active attacker may have the ability to do damage but just not in the way you are thinking

Can you, please, provide an example of such way? Hypothetical will do.

I'm commenting on this because it's just disappointing that the only legit scrypt library for Node doesn't offer a simple, batteries-included way to generate and verify a clean scrypt hash with meta info included (like numerous other standard-de-facto libraries do in other languages).

Instead of dropping a couple of new lines in my code and moving on with my day, I now have to debate whether I should stick to the convention and write my own wrapper (which is more likely to turn out to be unsafe, since it's not scrutinized by the community; whether the task at hand is trivial or not is irrelevant), or put my faith into the assumption that the same database won't be used by some other program written in another language (and if I end up being wrong, somebody will have to waste even more time on implementing these extra layers in another language).

**Comment by barrysteyn** [comment]
@jeremejevs 
> What's his rationale? Is it published anywhere?

Honestly, I don't care about why he did this. I do know he is a very good cryptographer, and I do know that he would not have done it if it in any way weakened the security.

> I'm commenting on this because it's just disappointing that the only legit scrypt library for Node doesn't offer a simple, batteries-included way to generate and verify a clean scrypt hash with meta info included (like numerous other standard-de-facto libraries do in other languages).

The `scrypt` method does what you describe. It just uses HMAC on top of it. If you feel so badly about this (why I don't know), then use the `hash` method to get a pure scrypt hash, and then compare it way.

> Instead of dropping a couple of new lines in my code and moving on with my day, I now have to debate whether I should stick to the convention and write my own wrapper 

Glad you appreciate the hard work I put into this module!!!! I have no idea what you are on about. Use `scrypt` function and get on with your day.

> or put my faith into the assumption that the same database won't be used by some other program written in another language (and if I end up being wrong, somebody will have to waste even more time on implementing these extra layers in another language).

Again, I have no idea what the above means??

**Comment by jeremejevs** [comment]
Okay, I'll try rephrasing it: I want the convenience of `kdf` + `kdfVerify` (which do the serialization and deserialization of the params + salt + hash for me) without SHA-256 and HMAC on top of it. Of course, I can just write my own `kdfVanilla` + `kdfVanillaVerify` on top of `hash`, that's a trivial task, but it's a real shame that these don't come out of the box.

The reason why I don't want HMAC so much is that then it makes it harder to switch to another language later on (which is a real possibility in the project I'm working on, for example), e.g. Go.

Since I mention Go, you might notice that [their scrypt package](https://godoc.org/golang.org/x/crypto/scrypt) doesn't offer any convenience functions at all, but that's because they left it to the [userland](https://github.com/elithrar/simple-scrypt). This lib, however, already has the convenience functions in it, just not the mainstream flavor, which is odd (and there's no fork / wrapper out there which adds those, as far as I can see).

**Comment by barrysteyn** [comment]
So if I understand you, what you really want is for this version of `scrypt` to use the same protocol for making and deriving a key as the Go version. Seeing as that most other language bindings/libraries (admittedly, I have only looked at the C and Python libraries) do not do this, can you give me a better reason other than it just working with Go.

Regarding the security, please look through his C source code, he recommends using it like this. One other thing: When you say vanilla, do you mean the straight forward hash? You do know that this is provided in the module?

**Comment by jeremejevs** [comment]
It doesn't have to be the same protocol, since there's no standard, but anything [MCF-like](http://pythonhosted.org/passlib/modular_crypt_format.html) would be fine. [`bcrypt` does MCF out of the box](https://en.wikipedia.org/wiki/Bcrypt), and then some `scrypt` libs mimic `bcrypt` in at very least [Java](https://github.com/wg/scrypt/blob/master/src/main/java/com/lambdaworks/crypto/SCryptUtil.java#L18), [Go](https://github.com/elithrar/simple-scrypt/blob/master/scrypt.go#L95), [Ruby](https://github.com/pbhogan/scrypt#how-to-use-scrypt), [Python](https://github.com/jvarho/pylibscrypt/blob/master/pylibscrypt/tests.py#L74), [PHP](https://github.com/DomBlack/php-scrypt/blob/master/scrypt.php#L147), [Haskell](https://github.com/informatikr/scrypt/blob/master/src/Crypto/Scrypt.hs#L141). None of them are compatible in the "drop-in" manner, but they all store the same information, making it easy to switch (just gotta run a conversion script on the existing data once).

I've looked at the original scrypt lib, and it seems to me that they (understandably) only care about Tarsnap's usecase: file encryption and transfer over unsecure networks. There's no comment anywhere on why have HMAC on top.

Yes, I'm aware of `hash`. That's not what I mean by vanilla, sorry for confusing "terminology".

If, for whatever reason, you believe that MCF [de]serialization doesn't belong in this library, then, please, do say so, and I'll go ahead and write a small wrapper, in a similar fashion to `simple-scrypt`.

**Comment by oconnore** [comment]
@jeremejevs it sounds like your issue here is with compatibility: in which case you should just store this as `$scrypt+hmac$...` and write a tiny Go function to check it. Done.

The reason I opened this issue was not because there is anything technically wrong, but that I think the construction is misleading -- the stack overflow description of it is likely to convince people that it has properties that it does not actually have. Barry disagrees, and that should be the end of it. I think if you want a particular MCF output/verifier construct, the correct place to do that is in a new pull request, not in this issue.

**Comment by barrysteyn** [comment]
Hi @oconnore and @jeremejevs  - No, I don't disagree with it. I am just very busy and I wanted to give a better answer. Long story short: Propose something, and let the community decide on it. If it is wanted/needed, then it will be my pleasure to implement it.

**Comment by jeremejevs** [comment]
@oconnore My doubts about HMAC are the source of my desire for an MCF-like solution, that's why I've chosen to comment on this issue (as to not fragment the discussion). If I was convinced that the HMAC layer makes is a win-win, then I wouldn't be surprised by the lack of a less secure solution.

@barrysteyn I'll probably do a pull request sometime this week, if my plans won't change.

**Comment by oconnore** [comment]
@barrysteyn oh, sorry for assuming :wink: Anyway, if I were to propose something, it would be: asking Colin to take a look at your [stack overflow post](http://security.stackexchange.com/questions/88678/why-does-node-js-scrypt-function-use-hmac-this-way/91050#91050). In particular, the bits about "active attackers" and "message integrity" seem dangerously close to implying that Alice can safely check passwords with `scryptdec_setup(...)`, even after Mallory has modified the `uint8_t header[96]` verifier. 

I expect the result will be a documentation fix to ensure no one uses this incorrectly. Otherwise there is little reason to fuss over a couple extra bytes and 3 SHA iterations.
