### ISSUE TITLE
Asynchronous verify throws instead of returning err object

### ISSUE THREAD

**Issue by rus0000** [barrysteyn/node-scrypt#52]
```javascript
var scrypt = require("scrypt");
var scryptParameters = scrypt.params(0.1);
scrypt.hash.config.outputEncoding = "base64";
scrypt.verify.config.hashEncoding = "buffer"; //will cause error

var hash = scrypt.hash("password", scryptParameters);

//Verify expects that hash would be a buffer
//Now it throws with wrong hash format message, instead of returning err object
scrypt.verify(hash, "password", function(err, result) {
    //Expecting err object here
}); //Throws with: 'Module addon argument error: key must be a buffer as specified by config'
```
Verify should throw only if there is no callback argument passed to it

**Comment by barrysteyn** [comment]
Hi @rus0000 

You have a good point. There should not be any exceptions thrown. The problem is that changing the code may break it to the point where people will have to rewrite their libraries again. Perhaps we can have a compatibility mode? I am up for suggestions, what do you think?

**Comment by BrandonZacharie** [comment]
It is documented that `scrypt.verify` expects a very specific format. Passing a `String` instead of a `Buffer` is clearly a programmer error. [Throwing in this situation follows Node's design guidelines](https://www.joyent.com/developers/node/design/errors#). However, I have not seen documentation around the fact that it throws. I recommend adding that instead.

**Comment by barrysteyn** [comment]
@BrandonZacharie Thanks for the article. I knew I had an uneasy feeling about changing this behaviour. I will document in a few days time...

**Comment by rus0000** [comment]
Function argument can be string or Buffer, and both are valid. Then, function is called with wrong argument type for given runtime configuration. Is it a programmer or operational error?

**Comment by barrysteyn** [comment]
@rus0000 and @BrandonZacharie We need to make a decision about this. In my original thinking, I thought that this was a programmer error. What do you guys think?

**Comment by BrandonZacharie** [comment]
The following is an excerpt of section _Bad input: programmer error or operational error?_ from [Node's design guidelines](https://www.joyent.com/developers/node/design/errors)

>Date.parse, for example, accepts a variety of inputs — that's basically the point. But for most other functions, we strongly recommend biasing towards being stricter rather than looser. The more your function tries to guess what the caller meant (using implied coercions, either as part of JavaScript or doing it explicitly in your function), the more likely it'll guess wrong. Instead of saving developers the effort required to be more explicit, you may well do something that wastes hours of the developer's time to debug.

The following is an excerpt of section _Operational errors vs. programmer errors_ from [Node's design guidelines](https://www.joyent.com/developers/node/design/errors)

>- *Programmer errors* are bugs in the program. These are things that can always be avoided by changing the code. They can never be handled properly (since by definition the code in question is broken).
  * tried to read property of "undefined"
  * called an asynchronous function without a callback
  * passed a "string" where an object was expected
  * passed an object where an IP address string was expected


According to that definition, we are most definitely talking about a programmer error. By design, programmers are expected to be aware of `hash`'s type. In contrast, if `scrypt.verify` were to infer the argument type, be asynchronous, _and_ yet still throw, I would take issue with that.

Ultimately, this is a design decision as both the current and proposed solutions are acceptable. Frankly, I'm arguing strictness here based purely on how I've interpreted what is written in the guidelines and the fact that we're talking about a crypto library; I really do prefer to receive my errors by argument. However, given the serious nature of this library, I suppose it's wiser to just follow the guidelines and know sooner rather than later when I've done something wrong.

**Comment by barrysteyn** [comment]
To note, that this is not an issue. This is being thrown because it is deemed a programmer error. This has been documented and in 29dabe135c2423f3a173aebc6d7e2deaf8d145db
