### ISSUE TITLE
Support integrating with other scrypt libraries, document HMAC method

### ISSUE THREAD

**Issue by dodtsair** [barrysteyn/node-scrypt#57]
This library might be used to generate the hash while another language and library is used to verify the hash.  To support this the website should include some demo code showing how the provided kdf method can be used to produce the same output as the hash function.  Specifically the algorithm used for the HMAC needs to be documented.

For example java library to do scrypt: 
https://github.com/wg/scrypt

**Comment by barrysteyn** [comment]
This is just a c++ addon, so if you want this feature, I suggest you contact the original author of Scrypt (Colin Percival). That being said, look at the source code for the HMAC algorithm.

I am updating this library to make it native Nodejs code (it is taking time because doing anything crypto related means you have go to be careful). I will try incorporate your requests in that library.
