### ISSUE TITLE
Global config changes can adversely affect unrelated parts of a system

### ISSUE THREAD

**Issue by fresheneesz** [barrysteyn/node-scrypt#67]
Its probably not a good idea to use global config variables like `script.hash.config` and `script.verify.config`. Since node.js caches modules, one system that uses `scrypt` could unknowingly break a different system if it changes the config. And if you have two places in your code where you want to use scrypt with different encodings, its currently very awkward to do.

Really, I would completely get rid of the encodings and require all inputs and outputs to be binary Buffers (which are easy enough to create and transcode).

**Comment by barrysteyn** [comment]
@fresheneesz Thanks for bringing this up. The module has been designed from the ground up to "mix and match" different encodings. I get it that binary buffers are easy to transcode and create, but I wanted people with crypto knowledge (not necessarily nodejs knowledge) to use this module. Crypto people are very familiar with specifying encodings. In my mind, it lowers the barrier to entry since people don't have to learn about nodes buffer system.

With regards to module caching, you definitely have a point. The classic way around this is for the module to export a function, and then for that function to be called.  Let me see if I can achieve this in a way that will not break current functionality.

**Comment by fresheneesz** [comment]
If you want to keep the encodings in, why not have the encodings as optional parameters to the `hash` and `verify` functions?

**Comment by barrysteyn** [comment]
Encodings are everywhere - in hash, verify and kdf. The thing is, I like a global config, but obviously, if someone uses require more than once, state should not follow.

**Comment by barrysteyn** [comment]
@fresheneesz I think the way to go here is to return a function in the module exports. Then the user would invoke the function to get their object:

`var scrypt = require('scrypt')();`

That would unfortunately not be backward compatible. Do you have any suggestions?

**Comment by fresheneesz** [comment]
Having encodings be passed in as optional parameters that fall back on the config you provided would be backwards compatible and would allow users to use parameters if/when they decide the need to do so. The downside is the global parameters still mess with people that don't pay attention to the reasons they might need to use parameters instead of the global defaults.

I'd suggest, if a user wants global config, the right way for them to do it is to make their own config module, and use the properties in the resulting object to pass into these functions. 

Something similar to your suggestion would be, if you set module.exports to a function that returns an instance of scrypt, have the encodings passed in there:

```
var scrypt = require('scrypt')('ascii', 'base64')
```

In this example, `script.hash` would use 'ascii' as the input encoding and 'base64' encoding, and `verify` the opposite. That way, the encodings are explicity (unless you want to leave them on the default 'buffer'), and you don't have to worry about expressing them correctly in either `hash`/`verify` or in config. Its much [DRYer](http://en.wikipedia.org/wiki/Don%27t_repeat_yourself) than:

```
var scrypt = require('scrypt')
scrypt.hash.config.keyEncoding = 'ascii'
scrypt.hash.config.outputEncoding = 'base64'
scrypt.verify.config.keyEncoding = 'ascii'
scrypt.verify.config.outputEncoding = 'base64'
```

For backwards compatibility, you could set the properties `hash` and `verify` on the function you're setting as `module.exports`, but if it were me, I'd increase the major version and let people change their code if they're upgrading. Keeping the old way of doing things is both difficult to maintain and makes the documentation more confusing. Speaking of which, I'd recommend moving documentation about the backwards-compatibility functions (`passwordHash`, `verifyHash`, etc) somewhere else, say the github wiki, and simply link to that if people want to do it the old way.

**Comment by barrysteyn** [comment]
You make some good points. I am going to think about this and rather tackle the other issues you have submitted first before I make such a big change.

**Comment by ironwallaby** [comment]
+1 to this. Global configs are a very bad idea, since multiple code chunks loading the same library can all override each other. (It's also *extremely* un-JavaScript-like.)

If it were me, I'd suggest the following function signatures:

    scrypt.hash(key, params, callback)
    scrypt.verify(hash, key, callback)

`key` should always either be a UTF8-encoded string, or a buffer. (If you want something else, convert it to a buffer manually.)

`hash` should always be returned or input as a Buffer. (If you want something else, call the convenient `toString` method of buffers.)

I think all of the encoding/config features the library provides actually causes the library to be *unhelpful*. It also adds complexity, and I'd rather `node-scrypt` be as minimal a wrapper as humanly possible, so there's less chance for bugs and it's easier for me to audit, since it's such a crucial piece of software for security.

**Comment by barrysteyn** [comment]
okay guys, I think I have seen the light and agree with you. Lets do this correct this time and sketch out a proper API. @fresheneesz and @ironwallaby - I will propose something, and lets debate it until we are all happy. This will be a version 5 and will therefore break backward compatibility, so lets just do it correct.

**Comment by fresheneesz** [comment]
Glad I make a bit of sense now and then ; ) . Happy to discuss!

**Comment by ironwallaby** [comment]
Yup, will be happy to provide feedback!

**Comment by BrandonZacharie** [comment]
Great discussion here. I also agree that the way to configure scrypt could use improvement. Listed are a few of ways to go about configuration and my thoughts about each:

**Per Module**
This is what is being done now. [This is a normal pattern when a designer chooses convention over configuration](http://www.wikiwand.com/en/Convention_over_configuration). I won't reiterate the con as that has already been mentioned. [Other ubiquitous libraries use this pattern; some of which do so while discouraging it's use (i.e. jQuery)](https://api.jquery.com/jquery.ajaxsetup/). I recommend we do the same here if only for backwards compatibility.

**Per Instance**
An example of this was provided earlier.
```javascript
var scrypt = require('scrypt')('ascii', 'base64')
```
This patterns avoids the con of the _per module_ pattern. However, it introduces two more. First, is _magic_. _magic_ is what I call something when in lack of a better explanation; no one without prior knowledge of scrypt or this discussion is likely to guess what happened on that line. Secondly, this pattern, by design, discards _convention over configuration_; developers will have to ensure correct configuration with every use which may encourage them to simply create their own module to abstract configuration logic. That's what I would do. IMO, that kind of defeats the point here.

**Per Call**
```javascript
scrypt.hash(key, params, config, callback);
```
or better yet
```javascript
scrypt.hash(key, config, callback);
```
This patterns avoids the cons of the _per module_ and _per instance_ pattern. We can achieve _convention over configuration_ with defaults for values not present in the configuration object. It also has the added benefit of not requiring any further changes in the method signature in the future as options are added and/or deprecated.

**Comment by barrysteyn** [comment]
Lets continue the debate in #72
