### ISSUE TITLE
scrypt functions are not really functions (typeof)

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [barrysteyn/node-scrypt#74]
```javascript
console.log(typeof require('scrypt').params); // object
console.log(typeof require('scrypt').hash); // object
// etc
```

This seems to break [promisification](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisification) in bluebird.

**Comment by barrysteyn** [comment]
It's on the fix list - so don't worry, it will become a proper function

**Comment by Demurgos** [comment]
I have to second this issue, the `instanceof` operator also fails.
It bothers me especially because I have to manually set the `apply` method to `Function.prototype.apply` in order to pass it to the promises lib I use (`Q`) and it doesn't feel neat.

I hope it's easy to fix and I would like to thank you for your work.

**Comment by barrysteyn** [comment]
This is corrected in version 5, which will be released either this week, or early next week. Thanks for bringing it up.
