### ISSUE TITLE
bluebird promises

### ISSUE THREAD

**Issue by AVVS** [barrysteyn/node-scrypt#96]
often people would use bluebird promises - imo its a good idea to use something like https://www.npmjs.com/package/native-or-bluebird in order to increase compatibility with older versions while allowing promise API to be used

**Comment by barrysteyn** [comment]
When we were discussing this library, a choice was made to use native promises. The problem being that importing a promise library would polute the global object (at least, this is what people more knowledgeable than myself said). So I am restricting this module to native promises by design. My thinking is if someone needs promises, then they should upgrade to a more recent version of node.

**Comment by AVVS** [comment]
This is actually locally scoped package and those people that have the native implementation would still use it. There is also a possibility to add a try/catch block and require the module, which would accomplish the same with more code.

**Comment by fresheneesz** [comment]
Bluebird promises are great, better than native actually. But its easy enough to promisify scrypts methods, so no real need to quibble over what's used.

**Comment by AVVS** [comment]
I was merely suggesting doing the bluebird/native approach where both would work based on which one is present on the system without the extra dependency :)

**Comment by barrysteyn** [comment]
I haven't looked at bluebird, so I can't state whether it is better than native promises, but I trust @fresheneesz, so if he says it's better, it is better :)

That being said, bluebird may be the new hotness, but in the JavaScript world, this lasts for about a month or so. What about when the next amazing promise implementation comes along? The only way I can keep some sanity for myself is to implement native promises. If people want promises, then they need to use Node that supports ES6. Otherwise they should roll their own (including using bluebird).

I am not doing this to be difficult, I am doing it because of the sanity.

**Comment by AVVS** [comment]
well, bluebird itself is around for a couple of years now, so thats not the new hotness as one might say. Sure we can do a wrapper method, its not hard, just extra lines of useless code, whereas only thing to actually make it work is this. Furthermore it doesn't really include the bluebird, unless it's already installed. Maybe I'm annoying, but imho simplicity of use without any sacrifices is something worth doing

```sh
npm i bluebird-or-native -S
```

```js
var Promise = require('bluebird-or-native');
```

**Comment by barrysteyn** [comment]
Vitaly, thank you very much for bringing this up. I really appreciate your efforts for trying to make this module better. Trust me, you are not annoying.

I am a lead engineer at a very large software company, and one of the biggest problems I face daily is legacy code. Admittedly, the documentation is not there, but even if there was documentation, it does not always capture the reasons why the decision was made. With that in mind, I am aiming to cut down on as much third party things as possible. If BB promises are great, then ES8 (or whatever) will eventually incorporate those ideas, and the native promises I have here will eventually encompass all the goodness you are describing. The alternative is that we implement BB promises like you have said, I get crazy busy and do not touch the code for six months, and then I decide to do some work and I break something.

So look at it as insurance for me.
