### ISSUE TITLE
Cannot build (failing posixconfig?)

### ISSUE THREAD

**Issue by dcousens** [barrysteyn/node-scrypt#98]
```
~$ uname -a
Linux arch 4.1.6-1-ARCH #1 SMP PREEMPT Mon Aug 17 08:52:28 CEST 2015 x86_64 GNU/Linux

~$ node -v
v4.1.0

~$ npm -v
3.3.3
```

```
~$ npm install scrypt
...
gyp: Call to 'scrypt/configuration/posixconfig' returned exit status 0. while trying to load binding.gyp
```

**Comment by barrysteyn** [comment]
Hi @dcousens 

Thanks for making contact, and sorry for taking so long to reply. Okay, lets try tackle this solution. I am working on the next new version of scrypt (it won't be a change to the API) which will use scrypt version 1.2.0 which should really help matters like your situation.

For now, could you please go into the scrypt module folder (found in node_modules) and find the posixconfig shell script, and run it manually. Tell me what happens.

**Comment by dcousens** [comment]
> For now, could you please go into the scrypt module folder (found in node_modules) and find the posixconfig shell script, and run it manually. Tell me what happens.

Easier said then done, I can't install it to do that.   I cloned the repo and ran the below:

``` bash
$ ./scrypt/configuration/posixconfig
-lrt
```

**Comment by barrysteyn** [comment]
And that is what is supposed to have happened. BTW: You don't need it to be successfully installed to run that command - It will download in your node_modules folder.

Okay, what was the return code. So once you have run that command, immediately type `echo $?` and tell me what number get's returned. It should be the VERY next thing you type after `./scrypt/configuration/posixconfig`

**Comment by dcousens** [comment]
> You don't need it to be successfully installed to run that command - It will download in your node_modules folder.

If `npm install scrypt` fails for me (as it does), then it does not remain in my `node_modules` folder.

``` bash
node_modules/scrypt$ ./scrypt/configuration/posixconfig
-lrt
node_modules/scrypt$ echo $?
0
```

**Comment by barrysteyn** [comment]
@dcousens This is a node-gyp problem. Please make sure you have the latest version, but even if you do have it, it may just not run nicely with your version of Linux (arch Linux).

I am going to close this issue because all the evidence points to either a faulty node install, a faulty node-gyp install or node-gyp not being able to run on arch linux. It could also be a python problem (gyp uses python, and so node-gyp also uses it).

**Comment by dcousens** [comment]
@barrysteyn this also fails on my OSX and Ubuntu servers,  but OK.

**Comment by barrysteyn** [comment]
Daniel, I can promise you that many people have this working on those
platforms. What version of Python are you using? I don't mind helping you
if you can prove to me that this is a genuine fault in the module. As of
now, I'm not convinced of that

**Comment by dcousens** [comment]
@barrysteyn well I'm accounting for 3 different developers in this situation,  on Ubuntu, Arch and OSX (2 different OSX machines actually).
This package works great if you don't use `node 4` or `npm 3`,  if I do use that,  I get the above.

**Comment by barrysteyn** [comment]
Okay, that is vital information you withheld. Node version 4 or npm 3. I
can definitely say it works for node version 4, but let me test npm 3 and
I'll get back to you

**Comment by dcousens** [comment]
@barrysteyn that information was literally all I posted in the OP.

**Comment by barrysteyn** [comment]
Yes, I see that now. I'll tell what I find

**Comment by barrysteyn** [comment]
I confirm, everything is working for me. I am using node version 4.1.0 and npm version 3.3.6

Honestly, I still think it is your node-gyp setup.

**Comment by dcousens** [comment]
@barrysteyn any hints as to what I can look for?
I haven't exactly modified the node-gyp setup on any of these machines.
Is there any explicit dependencies required other than `g++`?

**Comment by barrysteyn** [comment]
Hi @dcousens 

Okay, this is what I would do. Firstly, your error seems to be node-gyp related. I say this because it is complaining of something exiting with an error code of 0. But 0 is universally understood to designate that everything is okay. That is the reason I had you run the script manually and then `echo $?` - I wanted to see if it was returning `0`, and as you have proved, it was.

Back to your problem. node-gyp is the node version of gyp (stands for generate your project) which is a Google initiative at making a build tool to replace `make` in python. It is used heavily in building Chrome and the V8 engine, the latter being the reason why it is used to build node. Two things can go wrong:

 1. gyp, as mentioned above, relies on python, so node-gyp also needs python. Certain versions of python are known not to work nicely with node-gyp. I think python version 2.7 will definitely work. I am not sure about python 3. Check that you are not using python 3.
 2. Upgrade node-gyp - look at the npm entry (https://www.npmjs.com/package/node-gyp) - in fact, read this entry, it tells you how to install. You will want the latest version.

Tell me if you come right. If you don't then next step would be sending me a dump of your exact build process...

**Comment by barrysteyn** [comment]
Any update?

**Comment by dcousens** [comment]
The issue seems to be project dependent.
I have no issue installing it standalone.

Will report back when I figure it out.

**Comment by barrysteyn** [comment]
Okay, thanks for telling me. Please report back to me once you find out.
For my money, I would still investigate node-gyp. If you are using nvm,
perhaps it is setting the Python path to version 3 of Python.

**Comment by dcousens** [comment]
I alias `npm="npm --python=/usr/bin/python2.7"`,  so unless its somehow breaking the environment,  that shouldn't be the case.

**Comment by barrysteyn** [comment]
Okay, but does doing that ensure Python 2.7 will be used with node gyp.
There is any easy way to find out: node gyp will normally output to screen
what Python you it is using

**Comment by dcousens** [comment]
@barrysteyn `node-gyp` more or less out right breaks if I don't alias it,  and this has been fine for 100's of other dependencies I've had in the past.

**Comment by gavinhungry** [comment]
I'm having this problem as well, running Arch Linux 4.2.3, Node 4.2.1, npm 3.3.8 and node-gyp 3.0.3.

If included in your project, the [`touch`](https://www.npmjs.com/package/touch) library [adds a bin entry](https://github.com/isaacs/node-touch/blob/v1.0.0/package.json#L11), which apparently node-gyp respects, and then royally screws up `scrypt/configuration/posixconfig`, which of course is looking for GNU touch.

Just try:

    $ npm install touch scrypt

For now, I'm just installing scrypt first, then everything from package.json afterwards:

    $ npm install scrypt
    $ npm install

**Comment by dcousens** [comment]
ACK,  that seems to be the problematic dependency.

**Comment by barrysteyn** [comment]
@gavinhungry @dcousens Wow, that is interesting. Can you guys please specify in detail what is happening. I am working hard on the next major version of this module which will use version 1.2.0 of scrypt. It should fix lots of issues, but I will also need to run a config script again. If possible, I want to avoid what is happening here.

**Comment by gavinhungry** [comment]
@barrysteyn,

If you install the `touch` library alongside `scrypt`, `touch` adds a bin entry, which then overrides GNU touch (which is being used by `scrypt/configuration/posix_configuration/configure`, so when you try and touch a file, you're actually using the `touch` library). For whatever reason, `touch` [logs out some information](https://github.com/isaacs/node-touch/blob/master/bin/touch.js#L30) via `console.error` (even on success). This seems to lead to the "returned exit status 0" message seen above.

Options that I can see:
  1. Submit a pull request to `touch` to remove the success logging.
  2. In the configure script, use an absolute path to GNU touch (`/usr/bin/touch` on my system) instead of relying on `PATH` to take care of it. I don't know how robust this will be.
  3. Tell `node-gyp` to ignore bin entries. I don't know how to do this, but this would probably be the best solution.
  4. Dump error output when using touch (`touch $FILE 2> /dev/null`). This won't affect GNU touch, and won't change status codes, so your script will still function as usual.

If we can't tell `node-gyp` to ignore bin, I can write you a pull request for (4).

**Comment by barrysteyn** [comment]
@gavinhungry and @dcousens : Please can you do me a favour and clone v6, npm install, and then npm test and tell me if things are good.

Version 6 is going to seriously help fix things like you guys have experienced.

**Comment by gavinhungry** [comment]
@barrysteyn,

Your v6 module installs fine, even if I install the touch module beforehand. All tests seem to pass as well.

```
$ git clone -b v6 https://github.com/barrysteyn/node-scrypt
$ cd node-scrypt

$ npm install touch
$ npm install

$ npm test
[...]
73 passing
```

But, I'm having a problem installing v6 with `npm install`:
```
$ npm install https://github.com/barrysteyn/node-scrypt#v6
[...]
../src/scryptwrapper/keyderivation.c:27:20: fatal error: sha256.h: No such file or directory
```
NPM seems to not want to clone the `scrypt/scrypt-1.2.0` directory! It does clone `scrypt/scrypt-1.1.6` if I try to `npm install [...]#v5`. Not sure what's going on there. I'm using NPM version 3.5.0.

**Comment by barrysteyn** [comment]
Okay, thanks Gavin. I will look into it (I finally have some time)

**Comment by jasonvillalon** [comment]
Hi Guys,

Im also having exact problem.

Any updates on this?

tried on node 4.1.0, 5.2.0 and 5.3.0
npm v3.5.2
node-gyp v3.2.1

**Comment by jasonvillalon** [comment]
In my case, I Solved my problem by deleting my project/node_modules directory, then run "$ npm install scrypt", then run "$ npm install" to install other dependencies of my project.

**Comment by barrysteyn** [comment]
@jasonvillalon I am about to release version 6 (probably over the holidays) which will solve all these problems. Look out for it.

**Comment by gavinhungry** [comment]
@barrysteyn, any update? I still cannot install with `npm install [...]/node-scrypt#v6`, so I can't include scrypt into a package.json file. I'm stuck cloning and locally installing on deployment.

**Comment by jasonvillalon** [comment]
@gavinhungry my workaround for now is to install scrypt before installing other dependencies.

```
$ rm -rf node_modules
$ NODE_ENV=(development or production); npm install scrypt --save && npm install
```

**Comment by barrysteyn** [comment]
hi @jasonvillalon and @gavinhungry 

The only thing I need to do is update the documentation and then I will release v6. I will try to get this out of the door by next week. Sorry for the delay, really hectic at work.

**Comment by toddbluhm** [comment]
+1

**Comment by jasonvillalon** [comment]
i wonder when v6 will be release? :(

**Comment by barrysteyn** [comment]
v6 was released two days ago...
